"""Create Connections

Revision ID: 1bb268370800
Revises: b1154d17adb5
Create Date: 2019-04-18 21:03:56.464612

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1bb268370800'
down_revision = 'b1154d17adb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=True),
    sa.Column('to_person_id', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.Enum('mother', 'father', 'son', 'daughter', 'husband', 'wife', 'brother', 'sister', 'friend', 'coworker', name='connectiontype'), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    # ### end Alembic commands ###
